services:
    avathar.bbguildeq.installer:
        class: avathar\bbguildeq\game\eq_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildeq.provider:
        class: avathar\bbguildeq\game\eq_provider
        arguments:
            - '@avathar.bbguildeq.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
